name: portfolio

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
      pages: write
      id-token: write

jobs:
    deploye:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
    

        steps:

            - name: Check out Code
              uses: actions/checkout@v4

            - name: Setup the Github Pages
              uses: actions/configure-pages@v4

            - name: Uplode Static File
              uses: actions/upload-pages-artifact@v4
              with:
                path: '.'

            - name: Deploye state pages
              uses: actions/deploy-pages@v4

